### ISSUE TITLE
Stuck on "analyzing..."

### ISSUE THREAD

**Issue by hurdurderp** [ZaharX97/OWReveal#32]
Hello,
wanted to do some overwatch cases and got stuck on one demo, download worked fine, but it got stuck on the analyzing part
**Demourl** http://replay185.valve.net/730/003537840868251664663_1372133508.dem.bz2

Tested to parse it with https://github.com/ZaharX97/CSGOdemoPythonParser via 
`import DemoParser
parser = DemoParser.DemoParser("003537840868251664663_1372133508.dem", dump="dumpfile", ent="ALL")
parser.parse()` which worked fine

Tried it with "CSGOdemoPythonParser-master\example\round_stats.py" which gives the following error
`Traceback (most recent call last):
  File "E:\CSGOdemoPythonParser-master\round_stats.py", line 22, in <module>
    x.parse()
  File "E:\CSGOdemoPythonParser-master\DemoParser.py", line 139, in parse
    self._demo_ended_stuff()
  File "E:\CSGOdemoPythonParser-master\DemoParser.py", line 513, in _demo_ended_stuff
    p.print_one_entity(self.dump, self.get_resource_table())
  File "E:\CSGOdemoPythonParser-master\PrintStuff.py", line 95, in print_one_entity
    file.write("\n\nENTITY #{}: {} //".format(data.entity_id, data.class_name))
AttributeError: 'NoneType' object has no attribute 'entity_id'`

I don't know if it's a error for [OWReveal](https://github.com/ZaharX97/OWReveal) or [CSGOdemoPythonParser](https://github.com/ZaharX97/CSGOdemoPythonParser) 

Edit: Found another which completly analyses but only show round 1 with zero kills😅
http://replay189.valve.net/730/003537198747018592392_2096809545.dem.bz2

**Comment by ZaharX97** [comment]
I didnt update CSGOdemoPythonParser so it might not work properly 😄 
The first replay bug is fixed (couldn't find the rank for 1 player).
~Looking at the second now~
Edit:
Can't do anything about the second replay. The file is corrupted or didnt save properly and it's missing the start match event.
This is the third replay I see that it's missing some data, had one ~1 year ago that didn't have a round ending event (and final score in my app was something like 8-15 instead of 8-16)
